# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime_adi', models.CharField(max_length=250)),
                ('anlami', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Seviye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=250)),
                ('konu', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='kelime',
            name='seviye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formula.Seviye'),
        ),
    ]
